### ISSUE TITLE
2.3.0+ no longer handles empty strings as data sources

### ISSUE THREAD

**Issue by dpresling** [hashicorp/terraform-provider-cloudinit#104]
### Terraform CLI and Provider Versions

Terraform v1.3.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.16.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.1

### Terraform Configuration

```terraform
data "cloudinit_config" "cloud_config" {
  gzip          = false
  base64_encode = false

  part {
    content_type = "text/cloud-config"
    content = templatefile("${path.module}/files/cloud-config.yml.tpl", {
      region                    = data.aws_region.current.name
      environment               = var.environment
      domain                    = var.domain
    })
    merge_type = "list(append)+dict(recurse_array)+str()"
  }

  part {
    content_type = var.extra_cloud_config_type
    content      = var.extra_cloud_config_content
    merge_type   = "list(append)+dict(recurse_array)+str()"
  }
}

variable "extra_cloud_config_type" {
  description = "Extra cloud config type"
  default     = "text/cloud-config"
  type        = string
}

variable "extra_cloud_config_content" {
  description = "Extra cloud config content"
  default     = ""
  type        = string
}
```

### Expected Behavior

In 2.2.0 and earlier the empty string was handled and terraform moved on. 

### Actual Behavior

In 2.3.0+ the empty string for `extra_cloud_config_content` is not handled and gives the following error

```╷
│ Error: Invalid Attribute Value Length
│
│   with module.prometheus.data.cloudinit_config.cloud_config,
│   on ../../../modules/prometheus/data.tf line 37, in data "cloudinit_config" "cloud_config":
│   37:     content      = var.extra_cloud_config_content
│
│ Attribute part[1].content string length must be at least 1, got: 0
╵
```

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Additional Information

Setting the lock file to 2.2.0 allows this to work properly. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by austinvalle** [comment]
Hi there @dpresling 👋🏻, thanks for the detailed report and sorry you're running into this issue, I'll take a look at it.

Do you mind sharing some info on the scenario when you'd want to use an empty content for a `part` block? So I can document it with the upcoming fix.

Thanks!

**Comment by dpresling** [comment]
Thanks! 

We have a full stack of various modules that make use of the cloudinit provider and we set each module up with the same data and variable templates as above. In some modules we add extra cloud_config data and some we don't. By keeping the same template across all modules we only have to modify the inputs for each module when we want to add extra cloud_config data. 

Happy to be directed to a better way of doing it but it has worked for us up until now.

**Comment by dpresling** [comment]
Thanks for an amazingly quick turn around @austinvalle. Very much appreciated.

**Comment by austinvalle** [comment]
@dpresling Thanks for the info! We just pushed a new release `v2.3.2` that bug (might take an hour or so to show up in the registry, we're having some issues with syncing right now), I'll check back in tomorrow if it's not available in the registry by then.

Responding to your note about other possible ways to approach the module, you _could_ look into refactoring your module to use a `dynamic` block and only conditionally add the extra `part` block with `for_each`: https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks. This however would add additional complexity to your module that might not be ideal, as overusing dynamics can make your config difficult to read.

That being said, our intent with release `v2.3.0+` was to keep the original functionality, as we were only changing internals, so thank you for reporting this bug!

**Comment by austinvalle** [comment]
Hi @dpresling, `v2.3.2` is still not available as we're having some internal issues with our registry syncing new releases. I will keep in contact with the team investigating the issue and let you know when that new version is available.

Apologies for the delay and thanks for your patience!

**Comment by austinvalle** [comment]
@dpresling - Last ping 😆, `v2.3.2` is released now!

https://registry.terraform.io/providers/hashicorp/cloudinit/latest/docs

**Comment by dpresling** [comment]
Awesome! Thanks again!
