### ISSUE TITLE
Request for a binary version for darwin_arm64 (Apple Silicon) 

### ISSUE THREAD

**Issue by netflash** [hashicorp/terraform-provider-cloudinit#67]
### Terraform CLI and Provider Versions

n/a

### Use Cases or Problem Statement

```
- Installed hashicorp/cloudinit v2.2.0 (signed by HashiCorp)
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a
│ package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.
╵

ERRO[0029] 1 error occurred:
	* exit status 1
```

### Proposal

Can you please compile a binary for M1?

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
Hi @netflash 👋 Thank you for reporting this and sorry you ran into trouble here.

You are correct that there is a missing darwin/arm64 binary for a provider, however the error here is trying to indicate an issue with the _template_ provider:

> │ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a
│ package available for your current platform, darwin_arm64.

The [template provider](https://registry.terraform.io/providers/hashicorp/template) itself is [archived](https://github.com/hashicorp/terraform-provider-template/issues/85), where replacement of its functionality is expected to be done via this cloudinit provider for cloudinit templates and the Terraform configuration language [`templatefile()` function](https://www.terraform.io/language/functions/templatefile).

If you have any questions about migrating to these, my suggestion would be to raise a topic on [HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27) where more folks may be able to answer questions. 👍

**Comment by netflash** [comment]
@bflad I'm sorry. You are 100% correct.
It was my attempt to migrate from the old provider to the new one due to the cloudidint resources.
Apparently, I didn't clean up the old part in the files properly, that's why I got the error.

**Comment by redouane-dev** [comment]
Hi @netflash, could you provide more details on how you did the cleanup?

**Comment by DanielRDias** [comment]
> Hi @netflash, could you provide more details on how you did the cleanup?

I had the same problem. It got fixed after deleting the ".terraform" folder. Even after updating all references to use the new templatefile function, data "cloudinit_config", terraform.required_providers and .terraform.lock.hcl it was still causing problems because of the cached ".terraform" folder.
