### ISSUE TITLE
Missing image in README

### ISSUE THREAD

**Issue by BzSpi** [hashicorp/terraform-provider-cloudinit#80]
### Terraform CLI and Provider Versions

all

### Terraform Configuration

```terraform
n/a
```

### Expected Behavior

n/a

### Actual Behavior

n/a

### Steps to Reproduce

n/a

### How much impact is this issue causing?

Medium

### Additional Information

Hello,

The image in the README file previously [here](https://camo.githubusercontent.com/1c9b3273bad04255deba686917182886c66f72d39c9ab6c863feff5dac48a2c6/68747470733a2f2f63646e2e7261776769742e636f6d2f6861736869636f72702f7465727261666f726d2d776562736974652f6d61737465722f636f6e74656e742f736f757263652f6173736574732f696d616765732f6c6f676f2d6861736869636f72702e737667) does not exist anymore.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by austinvalle** [comment]
Hi there @BzSpi! 👋🏻

Thanks for the issue report, this image was a logo and will be removed with an upcoming PR.
